### 呼叫後只建構 Person，重複呼叫重複建構
GET https://localhost:7182/person

### 呼叫後只建構 Taiwanese，重複呼叫重複建構
GET https://localhost:7182/taiwanese

### 以上兩次呼叫都不會建構 PersonOnSingleton
# 只有該API被呼叫才會建構 PersonOnSingleton，且重複呼叫並不會重複建構
GET https://localhost:7182/persononsingleton
